# Generated by Django 2.2.1 on 2019-05-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Second',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_one', models.CharField(max_length=30)),
                ('field_two', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_one', models.CharField(max_length=30)),
                ('field_two', models.CharField(max_length=30)),
                ('second', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Second')),
            ],
        ),
    ]
